version: '3'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
    - ./server/.env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
    - ./client/.env
     
